version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ProtectedData
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123qweasdzxc
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:1234
    volumes:
      - .:/protecteddata
    ports:
      - "1234:5678"
    depends_on:
      - db